experimentalTernaries: true
semi: false
singleAttributePerLine: true
importOrder:
  - <THIRD_PARTY_MODULES>
  - "^[../]"
  - "^[./]"
importOrderSeparation: true
plugins:
  - prettier-plugin-tailwindcss
  - "@trivago/prettier-plugin-sort-imports"
