experimentalTernaries: true
semi: false
singleAttributePerLine: true
overrides:
  - files:
      - "**/.{ts,tsx}"
    options:
      htmlWhitespaceSensitivity: ignore
      plugins:
        - prettier-plugin-tailwindcss
        - "@trivago/prettier-plugin-sort-imports"
