experimentalTernaries: true
semi: false
singleAttributePerLine: true
overrides:
  - files:
      - "packages/web/**/.{ts,tsx}"
    options:
      htmlWhitespaceSensitivity: ignore
      plugins:
        - prettier-plugin-tailwindcss
