experimentalTernaries: true
semi: false
singleAttributePerLine: true
useTabs: true
importOrder:
  - <THIRD_PARTY_MODULES>
  - "^[~/]"
  - "^[../]"
  - "^[./]"
importOrderSeparation: true
# tailwindStylesheet: "./src/index.css"
plugins:
  - "@trivago/prettier-plugin-sort-imports"
  # - prettier-plugin-tailwindcss
overrides:
  - files: "*.yaml"
    options:
      tabWidth: 2
