bracketSameLine: true
experimentalTernaries: true
semi: false
singleAttributePerLine: true
trailingComma: es5
useTabs: true
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
      - "*.md"
    options:
      tabWidth: 2
      useTabs: false
  - files:
      - "package.json"
    options:
      tabWidth: 2
      useTabs: false
  - files:
      - "*.jsx"
      - "*.tsx"
    options:
        htmlWhitespaceSensitivity: ignore
plugins:
  - prettier-plugin-tailwindcss
