experimentalTernaries: true
semi: false
singleAttributePerLine: true
overrides:
  - files:
      - "*.jsx"
      - "*.tsx"
    options:
      htmlWhitespaceSensitivity: ignore
plugins:
  - prettier-plugin-tailwindcss
