/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as userTestavataruploadImport } from './routes/(user)/test_avatar_upload'
import { Route as userProfileImport } from './routes/(user)/profile'
import { Route as songSongImport } from './routes/(song)/song'
import { Route as userProfileEditImport } from './routes/(user)/profile_.edit'
import { Route as userProfileUsernameImport } from './routes/(user)/profile_.$username'
import { Route as songSongIdImport } from './routes/(song)/song_.$id'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const userTestavataruploadRoute = userTestavataruploadImport.update({
  id: '/(user)/test_avatar_upload',
  path: '/test_avatar_upload',
  getParentRoute: () => rootRoute,
} as any)

const userProfileRoute = userProfileImport.update({
  id: '/(user)/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const songSongRoute = songSongImport.update({
  id: '/(song)/song',
  path: '/song',
  getParentRoute: () => rootRoute,
} as any)

const userProfileEditRoute = userProfileEditImport.update({
  id: '/(user)/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRoute,
} as any)

const userProfileUsernameRoute = userProfileUsernameImport.update({
  id: '/(user)/profile_/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRoute,
} as any)

const songSongIdRoute = songSongIdImport.update({
  id: '/(song)/song_/$id',
  path: '/song/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/(song)/song': {
      id: '/(song)/song'
      path: '/song'
      fullPath: '/song'
      preLoaderRoute: typeof songSongImport
      parentRoute: typeof rootRoute
    }
    '/(user)/profile': {
      id: '/(user)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof userProfileImport
      parentRoute: typeof rootRoute
    }
    '/(user)/test_avatar_upload': {
      id: '/(user)/test_avatar_upload'
      path: '/test_avatar_upload'
      fullPath: '/test_avatar_upload'
      preLoaderRoute: typeof userTestavataruploadImport
      parentRoute: typeof rootRoute
    }
    '/(song)/song_/$id': {
      id: '/(song)/song_/$id'
      path: '/song/$id'
      fullPath: '/song/$id'
      preLoaderRoute: typeof songSongIdImport
      parentRoute: typeof rootRoute
    }
    '/(user)/profile_/$username': {
      id: '/(user)/profile_/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof userProfileUsernameImport
      parentRoute: typeof rootRoute
    }
    '/(user)/profile_/edit': {
      id: '/(user)/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof userProfileEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/song': typeof songSongRoute
  '/profile': typeof userProfileRoute
  '/test_avatar_upload': typeof userTestavataruploadRoute
  '/song/$id': typeof songSongIdRoute
  '/profile/$username': typeof userProfileUsernameRoute
  '/profile/edit': typeof userProfileEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/song': typeof songSongRoute
  '/profile': typeof userProfileRoute
  '/test_avatar_upload': typeof userTestavataruploadRoute
  '/song/$id': typeof songSongIdRoute
  '/profile/$username': typeof userProfileUsernameRoute
  '/profile/edit': typeof userProfileEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/(song)/song': typeof songSongRoute
  '/(user)/profile': typeof userProfileRoute
  '/(user)/test_avatar_upload': typeof userTestavataruploadRoute
  '/(song)/song_/$id': typeof songSongIdRoute
  '/(user)/profile_/$username': typeof userProfileUsernameRoute
  '/(user)/profile_/edit': typeof userProfileEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/song'
    | '/profile'
    | '/test_avatar_upload'
    | '/song/$id'
    | '/profile/$username'
    | '/profile/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/song'
    | '/profile'
    | '/test_avatar_upload'
    | '/song/$id'
    | '/profile/$username'
    | '/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/(song)/song'
    | '/(user)/profile'
    | '/(user)/test_avatar_upload'
    | '/(song)/song_/$id'
    | '/(user)/profile_/$username'
    | '/(user)/profile_/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  songSongRoute: typeof songSongRoute
  userProfileRoute: typeof userProfileRoute
  userTestavataruploadRoute: typeof userTestavataruploadRoute
  songSongIdRoute: typeof songSongIdRoute
  userProfileUsernameRoute: typeof userProfileUsernameRoute
  userProfileEditRoute: typeof userProfileEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  songSongRoute: songSongRoute,
  userProfileRoute: userProfileRoute,
  userTestavataruploadRoute: userTestavataruploadRoute,
  songSongIdRoute: songSongIdRoute,
  userProfileUsernameRoute: userProfileUsernameRoute,
  userProfileEditRoute: userProfileEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/auth",
        "/(song)/song",
        "/(user)/profile",
        "/(user)/test_avatar_upload",
        "/(song)/song_/$id",
        "/(user)/profile_/$username",
        "/(user)/profile_/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/(song)/song": {
      "filePath": "(song)/song.tsx"
    },
    "/(user)/profile": {
      "filePath": "(user)/profile.tsx"
    },
    "/(user)/test_avatar_upload": {
      "filePath": "(user)/test_avatar_upload.tsx"
    },
    "/(song)/song_/$id": {
      "filePath": "(song)/song_.$id.tsx"
    },
    "/(user)/profile_/$username": {
      "filePath": "(user)/profile_.$username.tsx"
    },
    "/(user)/profile_/edit": {
      "filePath": "(user)/profile_.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
